### ISSUE TITLE
version conflict, compilation failure

### ISSUE THREAD

**Issue by lesbleus2007** [merks/Xcore#2]
Which version of eclipse/emf/xtext should I be using to compile Xcore?

I'm using Indigo 3.7 CR1, EMF 2.7.0/2.7.1 and Xtext 2.0.1, but I run into compilation failures:
examples: 
    org.eclipse.emf.ecore.xcore.ui.EmptyXcoreProjectWizard.modifyWorkspace not overriding any method
    org.eclipse.emf.codegen.util.ImportManager.shouldImport undefined

```
org.eclipse.xtext.resource.IDerivedStateComputer undefined 
org.eclipse.emf.ecore.EDataType.Internal undefined
```

Otherwise Xcore seems to do exactly what I'm looking for!
Keep up the good work guys!

**Comment by merks** [comment]
You need to use the HEAD version of EMF along with these patches

```
https://bugs.eclipse.org/bugs/show_bug.cgi?id=354245
```

And the stable build for the latest version of Xtext.

**Comment by lesbleus2007** [comment]
Thanks for the fast response! I'll give it a try ASAP.
