### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by frankbenoit** [merks/Xcore#4]
Hi

there are no commits since 9 years.
So I wonder if XCore is a living project and it is worth looking into it, maybe use it in new projects.

Is this the original XCore repos or is it maintained elsewhere now?
What is the current status of the XCore?

Frank

**Comment by szarnekow** [comment]
Hi @frankbenoi, 
Xcore is now part of EMF and maintained at Eclipse: https://github.com/eclipse/emf/tree/master/plugins/org.eclipse.emf.ecore.xcore

**Comment by szarnekow** [comment]
Closing
